[project]
name = "ff14alram"
version = "0.2.0"
description = ""
authors = [Kaku"]
requires-python = ">=3.11"
dependencies = [
    "discord.py>=2.5.2",
    "flask>=3.1.0",
    "pytz",
    "apscheduler"
]
